### ISSUE TITLE
'Network/advertise_descriptor.h' file not found

### ISSUE THREAD

**Issue by phhai1710** [daltoniam/Starscream#878]
I got this error when I use this framework (v4.0.4) to build an MacOS app on my Macbook Pro 2019(11.2.3). It is working on my old Macbook pro 2017(11.2.3). I have tried v3.1.1 and it work well on both machines

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Network.h"
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Network.framework/Headers/Network.h:16:10: error: 'Network/advertise_descriptor.h' file not found
#include <Network/advertise_descriptor.h>
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Network.framework/Headers/Network.h:16:10: note: did not find header 'advertise_descriptor.h' in framework 'Network' (loaded from '/System/Library/PrivateFrameworks')
#include <Network/advertise_descriptor.h>
                ^
<unknown>:0: error: could not build Objective-C module 'Network'
```
