### PR TITLE
Xcode 12.5: Using ‘class’ keyword for protocol inheritance is deprecated; use ‘AnyObject’ instead

### PR DESCRIPTION
**Pull request by Emadgnia**
Hi @daltoniam, Thanks for considering this fix.
### Issue Link 🔗
https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID281

### Goals ⚽
Avoid having warning when you are building on Xcode 12.5.

### Implementation Details 🚧
Replace all the class with AnyObject due to the deprecation.

- https://github.com/apple/swift-evolution/blob/master/proposals/0156-subclass-existentials.md

### CODE REVIEW

**Review by the-indian-guy — APPROVED** [review]

**Comment by WyattMufson** [comment]
@acmacalister any eta on this?

**Comment by Julianvantveld** [comment]
Bump. Builds with Carthage not possible until this is fixed.

**Comment by Emadgnia** [comment]
@daltoniam do you have any update on this?

**Comment by Emadgnia** [comment]
hey, @acmacalister Could you also help out on this?

**Review by ranunez — APPROVED** [review]

**Comment by jonathanellis** [comment]
I believe this issue also causes the following (fatal) dyld error which I am experiencing when trying to link Starscream with a binary framework on Xcode <12.5:

```
dyld: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
```

It would be highly desirable to merge this ASAP...

**Review by jonathanellis — APPROVED** [review]

**Review by ken0nek — APPROVED** [review]

**Comment by ken0nek** [comment]
Hi @fassko,

Could you take a look at this pull request? It seems that many people need this fix 🙏 

Mentioning you because you handled the recent releases. Thank you.

**Review by ikarishinjigao — APPROVED** [review]

**Comment by fassko** [comment]
Sorry for my absence, I'm not using Websockets that much myself.

@ikarishinjigao or @ken0nek maybe you want to take this project over?
