### ISSUE TITLE
dyld: Symbol not found: __T0BOWV

### ISSUE THREAD

**Issue by joyqi** [daltoniam/Starscream#596]
Crashed after I updated from Xcode 9 to 10.1(10B61).

```
dyld: Symbol not found: __T0BOWV
  Referenced from: /Users/qining/Library/Developer/CoreSimulator/Devices/82860F65-3322-45B4-A19A-4AAEE392167C/data/Containers/Bundle/Application/EF30BBD3-2CF5-4A05-ADCB-81869FF123FE/SegmentFault.app/Frameworks/Starscream.framework/Starscream
  Expected in: /Users/qining/Library/Developer/CoreSimulator/Devices/82860F65-3322-45B4-A19A-4AAEE392167C/data/Containers/Bundle/Application/EF30BBD3-2CF5-4A05-ADCB-81869FF123FE/SegmentFault.app/Frameworks/libswiftCore.dylib
 in /Users/qining/Library/Developer/CoreSimulator/Devices/82860F65-3322-45B4-A19A-4AAEE392167C/data/Containers/Bundle/Application/EF30BBD3-2CF5-4A05-ADCB-81869FF123FE/SegmentFault.app/Frameworks/Starscream.framework/Starscream`
```

**Comment by fassko** [comment]
Which version of the Starscream are you using?

**Comment by joyqi** [comment]
Hi, it works now. I just clean the build directory and rebuild it with XCode 10 command line tools. Everything works fine.

**Comment by WSX1994** [comment]
> 嗨，现在有效。我只是清理构建目录并使用XCode 10命令行工具重建它。一切正常。

Hello, can you specify the solution, because I also encountered this problem. He can run on Xcode 9, but he made an error on Xcode 10.

**Comment by fassko** [comment]
Do you want to run on Xcode9? I think I misunderstood something here.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
